language: node_js
before_script:
  - echo $TRAVIS_COMMIT_RANGE
  - git diff --name-only $(echo $TRAVIS_COMMIT_RANGE | awk '{split($0,a,/\.\.\./); print a[1]}') $(echo $TRAVIS_COMMIT_RANGE | awk '{split($0,a,/\.\.\./); print a[2]}')
  - git log
  - npm install -g grunt-cli
  - npm install -g mocha
node_js:
  - "0.12"

