---

- name: get apache Directory Studio
  shell: "wget http://apache.mirrors.ionfish.org/directory/studio/2.0.0.v20161101-M12/ApacheDirectoryStudio-2.0.0.v20161101-M12-linux.gtk.x86_64.tar.gz"
  register: getstudio
- debug: var=getstudio

- name: get java
  shell: "wget --no-check-certificate --no-cookies --header \"Cookie: oraclelicense=accept-securebackup-cookie\" http://download.oracle.com/otn-pub/java/jdk/8u112-b15/jdk-8u112-linux-x64.tar.gz ; tar zxf jdk-8u112-linux-x64.tar.gz ; cd ApacheDirectoryStudio; ln -s /root/jdk1.8.0_112 jre ; yum -y install xorg-x11-font*"
  register: getjava
- debug: var=getjava

- debug: msg="to launch Apache Directory Studio -> ./ApacheDirectoryStudio"
- debug: msg="You should be able to connect using the Manager credentials {{OLCROOTDN}} with password {{OLCROOTPW | b64decode }}"
