---
INSTALL_DIR: "/sas/install"
NFS_SHARE_DIR: "{{ INSTALL_DIR }}/nfs"
SCRIPTS_DIR: "{{ INSTALL_DIR }}/scripts"
ANSIBLE_DIR: "{{ INSTALL_DIR }}/ansible"
PLAYBOOKS_DIR: "{{ ANSIBLE_DIR }}/playbooks"
VIYA_PLAYBOOK_DIR: "{{ ANSIBLE_DIR }}/sas_viya_playbook"
UTILITIES_DIR: "{{ INSTALL_DIR }}/bin"
ANSIBLE_KEY_DIR: "{{ NFS_SHARE_DIR }}/ansible_key"
READINESS_FLAGS_DIR: "{{ NFS_SHARE_DIR }}/readiness_flags"

LOGS_DIR: "/var/log/sas/install"

SASWORK_DIR: "/sastmp/saswork"
SAS_INSTALL_DIR: "/opt/sas"
SAS_INSTALL_DISK: ""
USERLIB_DIR: "/opt/sas/viya/config/data/cas"
USERLIB_DISK: ""
CASCACHE_DIR: "/sastmp/cascache"
CASCACHE_DISK: ""

DEPLOYMENT_MIRROR: ""
MIRROR_DIR: "{{ SAS_INSTALL_DIR }}/mirror"
MIRROR_URL: "http://{{ hostvars[groups['MirrorServer'][0]]['ansible_fqdn'] }}:8008/repo_mirror"
MIRROR_OPT: ""
DEPLOYTMENT_DATA_LOCATION: ""
TEMPORARY_SOE_FILE: "/tmp/SAS_Viya_playbook.tgz"

BACKUP_NFS_DIR: "{{ SAS_INSTALL_DIR }}/backups"
BACKUP_DIR: "/mnt/backups"


SAS_ORCHESTRATION_CLI_URL: "https://support.sas.com/installation/viya/34/sas-orchestration-cli/lax/sas-orchestration-linux.tgz"
VIRK_URL: "https://github.com/sassoftware/viya-ark.git"
VIRK_DIR: "{{ VIYA_PLAYBOOK_DIR }}/viya-ark"
VIYA_VERSION: "3.4"
VIRK_COMMIT_ID:
  "3.3": "9efbe65ed9a7cefdbf9db981b7974eee4f3b3933"
  "3.4": "d43bedba1095792bf604de12cfed6cb9118e8ae5"

