[mongod]

[mongod.net]
port = 27017
bind_ip = "0.0.0.0"
max_incoming_connections = 65536
wire_object_check = true
ipv6 = false

	[mongod.net.unix_domain_socket]
	enabled = true
	file_permissions = "0700"

[mongod.security]
cluster_auth_mode = ""
