releases:
- name: "bosh-dns"
  version: "1.7.0"
  url: "https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=1.7.0"
  sha1: "3046a07083751ae7740bbf7a25a1df6162628469"

addons:
- name: bosh-dns
  jobs:
  - name: bosh-dns
    release: bosh-dns
    properties:
      cache:
        enabled: true
      health:
        enabled: true
        server:
          tls: ((/dns_healthcheck_server_tls))
        client:
          tls: ((/dns_healthcheck_client_tls))
      api:
        server:
          tls: ((/dns_api_server_tls))
        client:
          tls: ((/dns_api_client_tls))
  include:
    stemcell:
    - os: ubuntu-trusty
    - os: ubuntu-xenial
- name: bosh-dns-windows
  jobs:
  - name: bosh-dns-windows
    release: bosh-dns
    properties:
      cache:
        enabled: true
      health:
        enabled: true
        server:
          tls: ((/dns_healthcheck_server_tls))
        client:
          tls: ((/dns_healthcheck_client_tls))
      api:
        server:
          tls: ((/dns_api_server_tls))
        client:
          tls: ((/dns_api_client_tls))
  include:
    stemcell:
    - os: windows2012R2
    - os: windows2016

variables:
- name: /dns_healthcheck_tls_ca
  type: certificate
  options:
    is_ca: true
    common_name: dns-healthcheck-tls-ca

- name: /dns_healthcheck_server_tls
  type: certificate
  options:
    ca: /dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - server_auth

- name: /dns_healthcheck_client_tls
  type: certificate
  options:
    ca: /dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - client_auth

- name: /dns_api_tls_ca
  type: certificate
  options:
    is_ca: true
    common_name: dns-api-tls-ca

- name: /dns_api_server_tls
  type: certificate
  options:
    ca: /dns_api_tls_ca
    common_name: api.bosh-dns
    extended_key_usage:
    - server_auth

- name: /dns_api_client_tls
  type: certificate
  options:
    ca: /dns_api_tls_ca
    common_name: api.bosh-dns
    extended_key_usage:
    - client_auth
