---
# Default cf-deployment deploys a (mostly) HA configuration.
# Use this override to only deploy single instance of each job,
# in a single Availability Zone.
- type: replace
  path: /instance_groups/name=consul/instances
  value: 1
- type: replace
  path: /instance_groups/name=nats/instances
  value: 1
- type: replace
  path: /instance_groups/name=diego-api/instances
  value: 1
- type: replace
  path: /instance_groups/name=uaa/instances
  value: 1
- type: replace
  path: /instance_groups/name=consul/instances
  value: 1
- type: replace
  path: /instance_groups/name=scheduler/instances
  value: 1
- type: replace
  path: /instance_groups/name=diego-cell/instances
  value: 1
- type: replace
  path: /instance_groups/name=router/instances
  value: 1
- type: replace
  path: /instance_groups/name=api/instances
  value: 1
- type: replace
  path: /instance_groups/name=cc-worker/instances
  value: 1
- type: replace
  path: /instance_groups/name=adapter/instances
  value: 1
- type: replace
  path: /instance_groups/name=doppler/instances
  value: 1
- type: replace
  path: /instance_groups/name=log-api/instances
  value: 1
- type: replace
  path: /instance_groups/name=tcp-router/instances
  value: 1

- type: replace
  path: /instance_groups/name=nats/azs
  value: [ z1 ]
- type: replace
  path: /instance_groups/name=diego-api/azs
  value: [ z1 ]
- type: replace
  path: /instance_groups/name=uaa/azs
  value: [ z1 ]
- type: replace
  path: /instance_groups/name=consul/azs
  value: [ z1 ]
- type: replace
  path: /instance_groups/name=scheduler/azs
  value: [ z1 ]
- type: replace
  path: /instance_groups/name=diego-cell/azs
  value: [ z1 ]
- type: replace
  path: /instance_groups/name=router/azs
  value: [ z1 ]
- type: replace
  path: /instance_groups/name=api/azs
  value: [ z1 ]
- type: replace
  path: /instance_groups/name=cc-worker/azs
  value: [ z1 ]
- type: replace
  path: /instance_groups/name=adapter/azs
  value: [ z1 ]
- type: replace
  path: /instance_groups/name=doppler/azs
  value: [ z1 ]
- type: replace
  path: /instance_groups/name=log-api/azs
  value: [ z1 ]
- type: replace
  path: /instance_groups/name=tcp-router/azs
  value: [ z1 ]
