---
- path: /releases/name=bosh/url
  type: replace
  value: https://mirror.azure.cn/bosh/bosh-compiled-release-tarballs/bosh-264.5.0-ubuntu-trusty-3468.13-20171214-231004-994547171-20171214231009.tgz%3FversionId%3D66MJhlOuDZn3SM18oBXxVP6DuV2BOXZi
- type: replace
  path: /releases/name=bosh-azure-cpi/url
  value: https://mirror.azure.cn/bosh/bosh-azure-cpi-release/bosh-azure-cpi-release-34.tgz
- type: replace
  path: /resource_pools/name=vms/stemcell/url
  value: https://mirror.azure.cn/bosh/bosh-azure-stemcells/bosh-stemcell-3468.13-azure-hyperv-ubuntu-trusty-go_agent.tgz
- path: /releases/name=os-conf/url
  type: replace
  value: https://mirror.azure.cn/bosh/os-conf/os-conf-release-18.tgz
