- path: /releases/name=cf-mysql/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/cf-mysql-36.14.0-ubuntu-trusty-3586.8-20180522-233703-70298358.tgz
- path: /releases/name=cf-mysql/version
  type: replace
  value: 36.14.0
- path: /releases/name=cf-mysql/sha1
  type: replace
  value: 804d3b88d3ef18ec3cd5811e07f9fd5e4b13cc54
- path: /releases/name=capi/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/capi-1.58.0-ubuntu-trusty-3586.8-20180522-230824-431393665.tgz
- path: /releases/name=capi/version
  type: replace
  value: 1.58.0
- path: /releases/name=capi/sha1
  type: replace
  value: 5c18df22bbd69b075eff3a145d89a48bcc33cda9
- path: /releases/name=binary-buildpack/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/binary-buildpack-1.0.18-ubuntu-trusty-3586.8-20180522-230037-477189301.tgz
- path: /releases/name=binary-buildpack/version
  type: replace
  value: 1.0.18
- path: /releases/name=binary-buildpack/sha1
  type: replace
  value: 14c631899059ce455c1fb21daf71776c2d0a2fcb
- path: /releases/name=cf-networking/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/cf-networking-1.13.0-ubuntu-trusty-3586.8-20180522-230440-735155429.tgz
- path: /releases/name=cf-networking/version
  type: replace
  value: 1.13.0
- path: /releases/name=cf-networking/sha1
  type: replace
  value: 0bb76df834959e26adaa7334d335222def03fd9c
- path: /releases/name=uaa/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/uaa-59-ubuntu-trusty-3586.8-20180522-230550-326035067.tgz
- path: /releases/name=uaa/version
  type: replace
  value: "59"
- path: /releases/name=uaa/sha1
  type: replace
  value: 6e9f5c12f3f97a9ea057034c3240c665b532c389
- path: /releases/name=nats/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/nats-24-ubuntu-trusty-3586.8-20180522-230255-492515604.tgz
- path: /releases/name=nats/version
  type: replace
  value: "24"
- path: /releases/name=nats/sha1
  type: replace
  value: 959d5bec9fff230fb55c01c1ffa1689bbd3b328f
- path: /releases/name=diego/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/diego-2.7.1-ubuntu-trusty-3586.8-20180523-212044-055901743.tgz
- path: /releases/name=diego/version
  type: replace
  value: 2.7.1
- path: /releases/name=diego/sha1
  type: replace
  value: 4f3896e1cfa2320444dd82e0c79b45df6fcc4088
- path: /releases/name=routing/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/routing-0.178.0-ubuntu-trusty-3586.8-20180522-230400-222261969.tgz
- path: /releases/name=routing/version
  type: replace
  value: 0.178.0
- path: /releases/name=routing/sha1
  type: replace
  value: 2efc80a91d2374b5a310ec9de5db9a3ffc9c02ab
- path: /releases/name=consul/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/consul-192-ubuntu-trusty-3586.8-20180522-230316-327039253.tgz
- path: /releases/name=consul/version
  type: replace
  value: "192"
- path: /releases/name=consul/sha1
  type: replace
  value: 5d0bbcf2dd76b27bcbdef70a91447e2ab00129b1
- path: /releases/name=cflinuxfs2/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/cflinuxfs2-1.209.0-ubuntu-trusty-3586.8-20180522-230210-513235603.tgz
- path: /releases/name=cflinuxfs2/version
  type: replace
  value: 1.209.0
- path: /releases/name=cflinuxfs2/sha1
  type: replace
  value: 5d87547c37b9be03b7065457a67260e4da7f05f0
- path: /releases/name=garden-runc/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/garden-runc-1.13.3-ubuntu-trusty-3586.8-20180522-230838-495905561.tgz
- path: /releases/name=garden-runc/version
  type: replace
  value: 1.13.3
- path: /releases/name=garden-runc/sha1
  type: replace
  value: 30a006d33f7e6604b30bc2f7235eb293c4f25d96
- path: /releases/name=loggregator/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/loggregator-102.1-ubuntu-trusty-3586.8-20180522-230429-030972053.tgz
- path: /releases/name=loggregator/version
  type: replace
  value: "102.1"
- path: /releases/name=loggregator/sha1
  type: replace
  value: 8dec0b747c5a75c5e3b93598b9402073965c72f8
- path: /releases/name=go-buildpack/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/go-buildpack-1.8.21-ubuntu-trusty-3586.8-20180522-230111-688730543.tgz
- path: /releases/name=go-buildpack/version
  type: replace
  value: 1.8.21
- path: /releases/name=go-buildpack/sha1
  type: replace
  value: 622adc14ed99977fea5b31b797da8f16b74159fe
- path: /releases/name=php-buildpack/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/php-buildpack-4.3.54-ubuntu-trusty-3586.8-20180522-230110-952275975.tgz
- path: /releases/name=php-buildpack/version
  type: replace
  value: 4.3.54
- path: /releases/name=php-buildpack/sha1
  type: replace
  value: f08c794c60eba058dc743dec37c29f3a3901ecfb
- path: /releases/name=cf-smoke-tests/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/cf-smoke-tests-40.0.5-ubuntu-trusty-3586.8-20180522-230222-707880781.tgz
- path: /releases/name=cf-smoke-tests/version
  type: replace
  value: 40.0.5
- path: /releases/name=cf-smoke-tests/sha1
  type: replace
  value: ed1477d3a054e0ab1ad31d785489fd3cb4e45c3c
- path: /releases/name=java-buildpack/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/java-buildpack-4.12-ubuntu-trusty-3586.8-20180522-230037-445655662.tgz
- path: /releases/name=java-buildpack/version
  type: replace
  value: "4.12"
- path: /releases/name=java-buildpack/sha1
  type: replace
  value: d52e1dfed8f52cdd0b70bdc35fd79ddfad885fc0
- path: /releases/name=ruby-buildpack/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/ruby-buildpack-1.7.18-ubuntu-trusty-3586.8-20180522-230117-594283835.tgz
- path: /releases/name=ruby-buildpack/version
  type: replace
  value: 1.7.18
- path: /releases/name=ruby-buildpack/sha1
  type: replace
  value: fa89fbeb24ed9abdcafe163dd1c97b9c4bcd8102
- path: /releases/name=statsd-injector/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/statsd-injector-1.3.0-ubuntu-trusty-3586.8-20180522-230300-617722413.tgz
- path: /releases/name=statsd-injector/version
  type: replace
  value: 1.3.0
- path: /releases/name=statsd-injector/sha1
  type: replace
  value: b685d7a9c82803a206bdd8966947eb3267aa898f
- path: /releases/name=nodejs-buildpack/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/nodejs-buildpack-1.6.23-ubuntu-trusty-3586.8-20180522-230038-838674142.tgz
- path: /releases/name=nodejs-buildpack/version
  type: replace
  value: 1.6.23
- path: /releases/name=nodejs-buildpack/sha1
  type: replace
  value: df96e3403b85936231b2297aa03bc91a14f744ee
- path: /releases/name=python-buildpack/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/python-buildpack-1.6.15-ubuntu-trusty-3586.8-20180522-230111-134896022.tgz
- path: /releases/name=python-buildpack/version
  type: replace
  value: 1.6.15
- path: /releases/name=python-buildpack/sha1
  type: replace
  value: d65fc86fdc6437cf14eb7f86cf145838dbda8e3c
- path: /releases/name=staticfile-buildpack/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/staticfile-buildpack-1.4.27-ubuntu-trusty-3586.8-20180522-230138-249731776.tgz
- path: /releases/name=staticfile-buildpack/version
  type: replace
  value: 1.4.27
- path: /releases/name=staticfile-buildpack/sha1
  type: replace
  value: c7787aae39dcd4f827f8f65fc224ea2143dd5c76
- path: /releases/name=dotnet-core-buildpack/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/dotnet-core-buildpack-2.0.6-ubuntu-trusty-3586.8-20180522-230130-469236989.tgz
- path: /releases/name=dotnet-core-buildpack/version
  type: replace
  value: 2.0.6
- path: /releases/name=dotnet-core-buildpack/sha1
  type: replace
  value: b873212404f01f345a479309776bfeea8f0ca47f
- path: /releases/name=cf-syslog-drain/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/cf-syslog-drain-6.5-ubuntu-trusty-3586.8-20180522-230406-789226959.tgz
- path: /releases/name=cf-syslog-drain/version
  type: replace
  value: "6.5"
- path: /releases/name=cf-syslog-drain/sha1
  type: replace
  value: b07298d361fd4133914c3ee329cc6f92fc34bcff
- path: /releases/name=capi/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=cf-mysql/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=binary-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=cf-networking/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=cf-smoke-tests/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=cf-syslog-drain/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=cflinuxfs2/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=consul/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=diego/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=dotnet-core-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=garden-runc/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=go-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=java-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=loggregator/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=nats/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=nodejs-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=php-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=python-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=routing/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=ruby-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=cf-mysql/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=staticfile-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=statsd-injector/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
- path: /releases/name=uaa/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.8"
