- path: /stemcells/alias=default/os
  type: replace
  value: ubuntu-xenial
- path: /stemcells/alias=default/version
  type: replace
  value: "97.16"
- path: /addons/name=loggregator_agent/include/stemcell/-
  type: replace
  value:
    os: ubuntu-xenial
- path: /addons/name=bpm/include/stemcell/-
  type: replace
  value:
    os: ubuntu-xenial
