- path: /releases/name=cf-mysql/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/cf-mysql-36.14.0-ubuntu-trusty-3586.16-20180606-173959-510251434.tgz
- path: /releases/name=cf-mysql/version
  type: replace
  value: 36.14.0
- path: /releases/name=cf-mysql/sha1
  type: replace
  value: 66cfbe5a686e0748a781b0ee9af0006c81d78834
- path: /releases/name=capi/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/capi-1.60.0-ubuntu-trusty-3586.16-20180606-225106-080088702.tgz
- path: /releases/name=capi/version
  type: replace
  value: 1.60.0
- path: /releases/name=capi/sha1
  type: replace
  value: 3a56adda3529889b4819d6f0bf3c00c6b27a5cec
- path: /releases/name=binary-buildpack/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/binary-buildpack-1.0.19-ubuntu-trusty-3586.16-20180606-174841-426579288.tgz
- path: /releases/name=binary-buildpack/version
  type: replace
  value: 1.0.19
- path: /releases/name=binary-buildpack/sha1
  type: replace
  value: d75eb4605441422f1fd3c7ffc7ac67fd868ad328
- path: /releases/name=cf-networking/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/cf-networking-1.13.0-ubuntu-trusty-3586.16-20180606-170814-608741188.tgz
- path: /releases/name=cf-networking/version
  type: replace
  value: 1.13.0
- path: /releases/name=cf-networking/sha1
  type: replace
  value: 301300c1bb973c2c32f9e92755771555aac06701
- path: /releases/name=uaa/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/uaa-59-ubuntu-trusty-3586.16-20180606-170936-46947203.tgz
- path: /releases/name=uaa/version
  type: replace
  value: "59"
- path: /releases/name=uaa/sha1
  type: replace
  value: 830786574fafdf0d1720728bf0b497bea3a5a9ee
- path: /releases/name=nats/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/nats-24-ubuntu-trusty-3586.16-20180606-170640-674186453.tgz
- path: /releases/name=nats/version
  type: replace
  value: "24"
- path: /releases/name=nats/sha1
  type: replace
  value: ead70e3bebc2f32d7f21a1f13a6ce24e0663a57f
- path: /releases/name=diego/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/diego-2.8.0-ubuntu-trusty-3586.16-20180606-171008-738543135.tgz
- path: /releases/name=diego/version
  type: replace
  value: 2.8.0
- path: /releases/name=diego/sha1
  type: replace
  value: 3aa96b63ecc99226b07374fd61bb644ec09a4aaf
- path: /releases/name=routing/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/routing-0.178.0-ubuntu-trusty-3586.16-20180606-170646-139997166.tgz
- path: /releases/name=routing/version
  type: replace
  value: 0.178.0
- path: /releases/name=routing/sha1
  type: replace
  value: 2b190c7f4449d9542c01091c3c70c566d508ab2e
- path: /releases/name=consul/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/consul-193-ubuntu-trusty-3586.16-20180606-170703-024769747.tgz
- path: /releases/name=consul/version
  type: replace
  value: "193"
- path: /releases/name=consul/sha1
  type: replace
  value: 599b4575e3fb5a246df84ecd8c361da8536642cf
- path: /releases/name=cflinuxfs2/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/cflinuxfs2-1.212.0-ubuntu-trusty-3586.16-20180606-170557-231577037.tgz
- path: /releases/name=cflinuxfs2/version
  type: replace
  value: 1.212.0
- path: /releases/name=cflinuxfs2/sha1
  type: replace
  value: a7388d6cd610dc6cbf4c64747c2c5291a8cdf4ca
- path: /releases/name=garden-runc/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/garden-runc-1.14.0-ubuntu-trusty-3586.16-20180606-171206-253098042.tgz
- path: /releases/name=garden-runc/version
  type: replace
  value: 1.14.0
- path: /releases/name=garden-runc/sha1
  type: replace
  value: 3e0cbc2450f64dd40994ab7b86c7686c0ba1256b
- path: /releases/name=loggregator/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/loggregator-102.2-ubuntu-trusty-3586.16-20180606-170042-881988778.tgz
- path: /releases/name=loggregator/version
  type: replace
  value: "102.2"
- path: /releases/name=loggregator/sha1
  type: replace
  value: 522f5fe722f01989770cfc6d7092f687cb764581
- path: /releases/name=go-buildpack/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/go-buildpack-1.8.23-ubuntu-trusty-3586.16-20180606-174838-287605142.tgz
- path: /releases/name=go-buildpack/version
  type: replace
  value: 1.8.23
- path: /releases/name=go-buildpack/sha1
  type: replace
  value: 30cfd4f9eed509115888d7b3190479ef809bd221
- path: /releases/name=php-buildpack/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/php-buildpack-4.3.56-ubuntu-trusty-3586.16-20180606-174837-617267146.tgz
- path: /releases/name=php-buildpack/version
  type: replace
  value: 4.3.56
- path: /releases/name=php-buildpack/sha1
  type: replace
  value: c359827943576730180583140b5b962fb79e7fd1
- path: /releases/name=cf-smoke-tests/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/cf-smoke-tests-40.0.5-ubuntu-trusty-3586.16-20180606-170548-795114594.tgz
- path: /releases/name=cf-smoke-tests/version
  type: replace
  value: 40.0.5
- path: /releases/name=cf-smoke-tests/sha1
  type: replace
  value: 99da8aeaea40ebd7cf98e7abff852528df6fd6d4
- path: /releases/name=java-buildpack/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/java-buildpack-4.12-ubuntu-trusty-3586.16-20180606-170416-946384215.tgz
- path: /releases/name=java-buildpack/version
  type: replace
  value: "4.12"
- path: /releases/name=java-buildpack/sha1
  type: replace
  value: 51e800db7c5d7f70bf5293cd2e2b50c11e438320
- path: /releases/name=ruby-buildpack/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/ruby-buildpack-1.7.19-ubuntu-trusty-3586.16-20180606-174846-319594759.tgz
- path: /releases/name=ruby-buildpack/version
  type: replace
  value: 1.7.19
- path: /releases/name=ruby-buildpack/sha1
  type: replace
  value: 9a06b59340b67af282209abeb562b7d69cb2e3ba
- path: /releases/name=statsd-injector/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/statsd-injector-1.3.0-ubuntu-trusty-3586.16-20180606-170613-065714425.tgz
- path: /releases/name=statsd-injector/version
  type: replace
  value: 1.3.0
- path: /releases/name=statsd-injector/sha1
  type: replace
  value: d590aa2ae299d32daec926368749bbc5621fb841
- path: /releases/name=nodejs-buildpack/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/nodejs-buildpack-1.6.25-ubuntu-trusty-3586.16-20180606-174841-105583708.tgz
- path: /releases/name=nodejs-buildpack/version
  type: replace
  value: 1.6.25
- path: /releases/name=nodejs-buildpack/sha1
  type: replace
  value: 9eb16871d605e4d02f443e1743e648add65fdbc8
- path: /releases/name=python-buildpack/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/python-buildpack-1.6.17-ubuntu-trusty-3586.16-20180606-174840-508487261.tgz
- path: /releases/name=python-buildpack/version
  type: replace
  value: 1.6.17
- path: /releases/name=python-buildpack/sha1
  type: replace
  value: 6310fd6ff6376434fd056ca385c37b92c030e89f
- path: /releases/name=staticfile-buildpack/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/staticfile-buildpack-1.4.28-ubuntu-trusty-3586.16-20180606-174837-112784209.tgz
- path: /releases/name=staticfile-buildpack/version
  type: replace
  value: 1.4.28
- path: /releases/name=staticfile-buildpack/sha1
  type: replace
  value: 088ad7d49783493a211b38ed7d2ef6a10eb5f766
- path: /releases/name=dotnet-core-buildpack/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/dotnet-core-buildpack-2.0.7-ubuntu-trusty-3586.16-20180606-174845-180451793.tgz
- path: /releases/name=dotnet-core-buildpack/version
  type: replace
  value: 2.0.7
- path: /releases/name=dotnet-core-buildpack/sha1
  type: replace
  value: 5562376c987f3a8e24ddea88b1b1f3f73a2bd2bc
- path: /releases/name=cf-syslog-drain/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/cf-syslog-drain-6.5-ubuntu-trusty-3586.16-20180606-170729-503553541.tgz
- path: /releases/name=cf-syslog-drain/version
  type: replace
  value: "6.5"
- path: /releases/name=cf-syslog-drain/sha1
  type: replace
  value: 154000b4a38325995a3159e402346c8bcef5965b
- path: /releases/name=capi/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=cf-mysql/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=binary-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=cf-networking/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=cf-smoke-tests/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=cf-syslog-drain/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=cflinuxfs2/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=consul/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=diego/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=dotnet-core-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=garden-runc/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=go-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=java-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=loggregator/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=nats/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=nodejs-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=php-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=python-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=routing/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=ruby-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=cf-mysql/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=staticfile-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=statsd-injector/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=uaa/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=bpm/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/bosh-setup/cf-deployment-compiled-releases/bpm-0.6.0-ubuntu-trusty-3586.16-20180606-214750-711562676.tgz
- path: /releases/name=bpm/version
  type: replace
  value: 0.6.0
- path: /releases/name=bpm/sha1
  type: replace
  value: 643baece0215f88066d2a98ce12fad6cfecf48d2
