---
- path: /releases/name=binary-buildpack/url
  type: replace
  value: https://mirror.azure.cn/bosh/binary-buildpack/binary-buildpack-release-1.0.15.tgz
- path: /releases/name=capi/url
  type: replace
  value: https://mirror.azure.cn/bosh/capi/capi-release-1.46.0.tgz
- path: /releases/name=cf-mysql/url
  type: replace
  value: https://mirror.azure.cn/bosh/cf-mysql/cf-mysql-release-36.10.0.tgz
- path: /releases/name=cf-networking/url
  type: replace
  value: https://mirror.azure.cn/bosh/cf-networking/cf-networking-release-1.9.0.tgz
- path: /releases/name=cf-smoke-tests/url
  type: replace
  value: https://mirror.azure.cn/bosh/cf-smoke-tests/cf-smoke-tests-release-39.tgz
- path: /releases/name=cf-syslog-drain/url
  type: replace
  value: https://mirror.azure.cn/bosh/cf-syslog-drain/cf-syslog-drain-release-4.tgz
- path: /releases/name=cflinuxfs2/url
  type: replace
  value: https://mirror.azure.cn/bosh/cflinuxfs2/cflinuxfs2-release-1.176.0.tgz
- path: /releases/name=consul/url
  type: replace
  value: https://mirror.azure.cn/bosh/consul/consul-release-190.tgz
- path: /releases/name=diego/url
  type: replace
  value: https://mirror.azure.cn/bosh/diego/diego-release-1.31.1.tgz
- path: /releases/name=dotnet-core-buildpack/url
  type: replace
  value: https://mirror.azure.cn/bosh/dotnet-core-buildpack/dotnet-core-buildpack-release-1.0.32.tgz
- path: /releases/name=garden-runc/url
  type: replace
  value: https://mirror.azure.cn/bosh/garden-runc/garden-runc-release-1.10.0.tgz
- path: /releases/name=go-buildpack/url
  type: replace
  value: https://mirror.azure.cn/bosh/go-buildpack/go-buildpack-release-1.8.15.tgz
- path: /releases/name=java-buildpack/url
  type: replace
  value: https://mirror.azure.cn/bosh/java-buildpack/java-buildpack-release-4.7.1.tgz
- path: /releases/name=loggregator/url
  type: replace
  value: https://mirror.azure.cn/bosh/loggregator/loggregator-release-99.tgz
- path: /releases/name=nats/url
  type: replace
  value: https://mirror.azure.cn/bosh/nats/nats-release-22.tgz
- path: /releases/name=nodejs-buildpack/url
  type: replace
  value: https://mirror.azure.cn/bosh/nodejs-buildpack/nodejs-buildpack-release-1.6.13.tgz
- path: /releases/name=php-buildpack/url
  type: replace
  value: https://mirror.azure.cn/bosh/php-buildpack/php-buildpack-release-4.3.46.tgz
- path: /releases/name=python-buildpack/url
  type: replace
  value: https://mirror.azure.cn/bosh/python-buildpack/python-buildpack-release-1.6.4.tgz
- path: /releases/name=routing/url
  type: replace
  value: https://mirror.azure.cn/bosh/cf-routing/cf-routing-release-0.169.0.tgz
- path: /releases/name=ruby-buildpack/url
  type: replace
  value: https://mirror.azure.cn/bosh/ruby-buildpack/ruby-buildpack-release-1.7.8.tgz
- path: /releases/name=staticfile-buildpack/url
  type: replace
  value: https://mirror.azure.cn/bosh/staticfile-buildpack/staticfile-buildpack-release-1.4.20.tgz
- path: /releases/name=statsd-injector/url
  type: replace
  value: https://mirror.azure.cn/bosh/statsd-injector/statsd-injector-release-1.0.30.tgz
- path: /releases/name=uaa/url
  type: replace
  value: https://mirror.azure.cn/bosh/uaa/uaa-release-53.tgz
